version: '4.0'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: noticehub_app
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-noticehub_user}:${POSTGRES_PASSWORD:-noticehub_password}@db:5432/${POSTGRES_DB:-noticehub_db}
    ports:
      - "5001:5001" 
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5001/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s 
    depends_on:
      - db
  ui:
    build:
      context: .
      dockerfile: Dockerfile
    command: streamlit run scripts/streamlit_app.py --server.port 8501
    container_name: noticehub_ui
    ports:
      - "8501:8501"
    depends_on:
      - app

  db:
    image: postgres:17-alpine 
    container_name: noticehub_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-noticehub_user} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-noticehub_password} 
      POSTGRES_DB: ${POSTGRES_DB:-noticehub_db} 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-noticehub_user} -d ${POSTGRES_DB:-noticehub_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data: 
